### ISSUE TITLE
Unable to clone repositories on servers which its domain name has only AAAA records.

### ISSUE THREAD

**Issue by be5invis** [msysgit/git#131]
The current msysgit, including `git` and built-in tools like `ssh`, cannot be used for ipv6-only remotes.

**Comment by jugmac00** [comment]
I have the exact same problem as outlined above. We are about to move our linux box to a new provider, which others only ipv6 connection. When I try to connect either via ssh or git clone I get the same error messages as above. Putty works, mobaxterm works, but I would really like to continue to use git bash. What are the plans in future? When t-b said, use plink or copssh - did he mean as standalone alternative or as plugin to git-bash? If latter one, who to do that?

**Comment by t-b** [comment]
The problem is that our ssh client(openssh) can not use IPv6. So in order to use ssh and IPv6, you might want to have a try with other ssh clients like plink or copssh.

The underlying technical limitation that ssh and IPv6 don't work together in our situation is quite deeply rooted so there is no ETA on when this is fixed.

**Comment by jugmac00** [comment]
Thank you for the information.

**Comment by dscho** [comment]
@be5invis @davux for the record, I just tested the following command in the [preview of Git for Windows](https://git-for-windows.github.io/#download)... It seems that the OpenSSH shipped with MSys2 supports IPv6:

```sh
$ ssh -6 fdda:dada:dada:dada::xxxx:xxxx
ssh: Could not resolve hostname fdda:dada:dada:dada::xxxx:xxxx: Name or service not known
```

**Comment by davux** [comment]
Thanks @dscho!

**Comment by dscho** [comment]
@davux have you actually tried yourself?

**Comment by davux** [comment]
I have, and I like it a lot, as it provides more recent commands, and more of them if you install the SDK and not just git-bash. I'm trying to have it integrated into my normal terminal (conemu) but you've already noticed that in a different issue!
