### ISSUE TITLE
perl debugging (perl -de 1) does not work (perl5db.pl and dumpvar.pl missing).

### ISSUE THREAD

**Issue by Dirk1966** [msysgit/git#134]
perl allows always debugging on the command line:
    perl -de 1
or
    perl -de 0
The necessary files for debugging
    perl5db.pl
and
    dumpvar.pl
were deleted with git commit c3b46a47f208:
http://code.google.com/p/msysgit/source/detail?r=c3b46a47f2086481c33c989fe418d7c01d553b72

These 2 files can not be created by downloading them for CPAN for instance, they are part of each perl interpreter.

Debugging perl is a necessary for instance if yo have a special problem during a check in on gerrit for instance (I use a "git review" with perl code).
It is a pity to have an interpreter with no possibility to debug.

Best regards,
Dirk Heumann

**Comment by Dirk1966** [comment]
Hi all,
both files are still in the repository and can be retrieved via
`$ git checkout c3b46a47f2086481c33c989fe418d7c01d553b72^ -- lib/perl5/5.8.8/dumpvar.pl`
`$ git checkout c3b46a47f2086481c33c989fe418d7c01d553b72^ -- lib/perl5/5.8.8/perl5db.pl`
Can someone explain how I make a pull request out of this?
The problem is, that even if you try to compile something for msysgit, you'll need perl, and because the perl is so old, many things do not work (I tried to compile perl 5.10 to 5.20 and already failed compiling necessary libraries).  You need the possibility to analyze debug failures in a big manner, therefore you need a perl debugger on the platform.
Best regards,
Dirk

**Comment by dscho** [comment]
> Can someone explain how I make a pull request out of this?

https://help.github.com/articles/using-pull-requests/
