### ISSUE TITLE
Optionally Configure git user name and email for current user during install

### ISSUE THREAD

**Issue by lawrancej** [msysgit/git#198]
It'd be nice if the installer for Windows configured the git user name and email address during installation, if the configuration is not already set.

**Comment by dscho** [comment]
@lawrancej please note that Git for Windows 1.x was retired, and the `/share/WinGit/release.sh` script moved to https://github.com/git-for-windows/build-extra/blob/master/installer/release.sh (in case you haven't given up on this feature yet).
