### ISSUE TITLE
Install puts a space after ';' in PATH?

### ISSUE THREAD

**Issue by codespear** [msysgit/git#202]
I think Git-1.9.4-preview20140611.exe changed my PATH to have spaces after each ';'.  This should in general be OK; but these spaces cause problems on my system.

**Comment by sschuberth** [comment]
Unable to reproduce. If you can, please use a tool like [Rapid Environment Editor](http://www.rapidee.com/en/download) to capture both `System` and `User` PATH environment variables before and after the installation of Git and copy them here.
