### ISSUE TITLE
Adding `man` to msysgit

### ISSUE THREAD

**Issue by schodge** [msysgit/git#203]
I would love to see `man` included in mysysgit, so that help can be viewed in the command line.  How difficult is the initial porting process and setting it up to build properly in the future?  I'd certainly be willing to lend effort to the task if its within my skill range.  Thanks.

**Comment by dscho** [comment]
MSys2 comes with `man`, and as a consequence, you can install it using `pacman -Sy man` with the [Git for Windows SDK](http://git-for-windows.github.io/#download-sdk). Please note that it is no reason for joy, as active participation of the people in this thread could have brought about `man` much earlier.
