### ISSUE TITLE
Frequent crashes and stackdumps, Win7

### ISSUE THREAD

**Issue by chillitom** [msysgit/git#206]
Git 1.9.2

I'm experiencing frequent crashes of git and related processes on Windows 7.  Two representative stack dumps below.  Can provide more if it will help.

Any ideas as to what might be causing these?

sh.exe:

MSYS-1.0.12 Build:2012-07-05 14:56
Exception: STATUS_ACCESS_VIOLATION at eip=765F422C
eax=00000009 ebx=765F0000 ecx=680C1034 edx=00000001 esi=680C1034 edi=680A1020
ebp=0100FDF8 esp=0100FDD8 program=C:\Program Files (x86)\Git\bin\sh.exe
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0100FDF8  765F422C  (765F0000, 00000003, 00000000, D9F89BC4)
0100FE58  765F403F  (765F0000, 00000003, 00000000, 007A5FF8)
0100FE78  76FC9930  (765F3FB1, 765F0000, 00000003, 00000000)
0100FF1C  76FED3DB  (680566D8, 00000000, 0100FF88, 68005502)
0100FF2C  76FED5C2  (00000000, 0100FF88, 680054D7, 0100FF80)
0100FF88  68005502  (680A4E68, 0100FFD4, 76FC9ED2, 680A4E68)
0100FF94  76A033AA  (680A4E68, 23E58309, 00000000, 00000000)
0100FFD4  76FC9ED2  (680054A8, 680A4E68, 00000000, 00000000)
0100FFEC  76FC9EA5  (680054A8, 680A1020, 77366377, 00000000)
End of stack trace

git.exe:

MSYS-1.0.12 Build:2012-07-05 14:56
Exception: STATUS_ILLEGAL_INSTRUCTION at eip=0235EFA8
eax=00AF15F0 ebx=00000000 ecx=0235806C edx=0235EFA8 esi=0028E09C edi=00000001
ebp=0028E0B0 esp=0028E080 program=C:\Program Files (x86)\Git\libexec\git-core\git.exe
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0028E0B0  0235EFA8  (63070000, 00000000, 023584B8, 00503118)
0028E0D0  77CC9930  (631F1E1C, 63070000, 00000000, 00000001)
0028E174  77CE8FBA  (00000001, 00410000, 0028E1CC, 0028E19C)
0028E188  77CE8E5C  (00000000, 77E8F3B0, FFFFFFFF, 0028E21C)
0028E19C  77697A0D  (00000001, 0028E1CC, 0028EEBC, 00AFA580)
0028E21C  6803FC4A  (00000001, 0028E294, 00000000, FFFFFFFF)
0028F4BC  68059A97  (00000000, 0028F59C, 0A6F0EC0, 0A0141F0)
0028F4FC  68059D3A  (00000000, 00000003, 0028F59C, 0A6F0EC0)
0028F52C  680104E5  (0028F59C, 0A6F0EC0, 0A0141F0, 68087475)
0028F55C  68010562  (0028F59C, 0A6F0EC0, 0028F99C, 6808458F)
0028F99C  6808459C  (0A703FA0, 0A6F0EC0, 0028F9FC, 6788C275)
0028F9FC  6788C286  (0A703F70, 0000000A, 00000001, 678412E3)
0028FA4C  6784139A  (0A703F70, 6787B8BF, 0A048A26, 00000001)
0028FB8C  6787B9B5  (00000000, 00000003, 0028FBAC, 677F3D2F)
0028FB9C  6784DD34  (0A012268, 00000000, 0028FCDC, 677F3A6E)
0028FBAC  677F3D2F  (00000001, 00000000, 0028FCC4, 00001000)
End of stack trace (more stack frames may be present)

**Comment by dscho** [comment]
Both stacktraces look like DLL range issues (which `rebase.exe` would fix) to me. Such problems should be fixed in [Git for Windows 2.x](http://git-for-windows.github.io/) which runs `rebase.exe` as part of the installation process.

Should the problem persist with Git for Windows 2.x, please follow [the advice on reporting issues there](http://git-for-windows.github.io/#contribute).
