### ISSUE TITLE
Latest install removes original Path and replaces it. (windows)

### ISSUE THREAD

**Issue by ZeerDonker** [msysgit/git#214]
Hello,

The latest install (downloaded it today), replaces all other things in the system path with the following: 
C:\Program Files (x86)\OpenSSH\bin;C:\Program Files (x86)\Git\cmd

(Example: vagrant 's  directory was taken out)

Kind regards,
Z

**Comment by sschuberth** [comment]
Unable to reproduce. If you can, please use a tool like [Rapid Environment Editor](http://www.rapidee.com/en/download) to capture both `System` and `User` PATH environment variables before and after the installation of Git and copy them here.
