### ISSUE TITLE
rebase fails on branch with spaces in name

### ISSUE THREAD

**Issue by blakekl** [msysgit/git#233]
Someone created a branch in our project that uses spaces in the name. Whenever I attempt a rebase  --all or dcommit now I'm presented with the following error: (update is an alias for rebase --all).

![error](https://cloud.githubusercontent.com/assets/1930170/3989445/f67fac32-28ba-11e4-9ae8-0a155eedf059.png)

My refs/remotes shows the offending branch:

![image](https://cloud.githubusercontent.com/assets/1930170/3989452/22830266-28bb-11e4-807a-88254cd4b319.png)

other users on linux running git-svn were able to rebase just fine.

**Comment by blakekl** [comment]
I ran into this again, so for myself, in case I run into it again, I had to delete the reference to the branch with spaces in it. We renamed that branch shortly after to use '_' instead of spaces. I think this way I just ignore the branch while it has the bad name, but I don't care about the 3 or 4 commits that I'm missing in that history.

rm .git/refs/remotes/<bad branch>
'git svn fetch' using the 1.8.3 portable after that works, but I'm guessing I can use any version after that.

**Comment by dscho** [comment]
I am pretty certain that nobody took care of this so far. Nevertheless, Git for Windows 1.x was retired. If anybody has time to work on this, please test with [Git for Windows 2.x](http://git-for-windows.github.io/) and if the problem indeed still persists, open a Pull Request there with a fix. Kidding. You can [open a ticket](http://git-for-windows.github.io/#contribute) but please note that I will expect you to do your share to fix the bug.
