### ISSUE TITLE
Fork error when launching Git Bash.vbs from portablegit 20140815

### ISSUE THREAD

**Issue by rpavlik** [msysgit/git#238]
This is on a Windows XP x64 system (industrial visualization machine, can't upgrade). With the latest portablegit, I get this when trying to launch `git bash.vbs`

```
H:\windows\Git-PortableGit-1.9.4-preview20140815\bin\sh.exe: *** fork: can't res
erve memory for stack 0x4A0000 - 0x6A0000, Win32 error 0
      0 [main] sh.exe" 1656 sync_with_child: child 472(0xE0) died before initial
ization with status code 0x1
     49 [main] sh.exe" 1656 sync_with_child: *** child state waiting for longjmp

sh.exe": fork: Resource temporarily unavailable
sh.exe"-3.1$
```

Doesn't matter if this is over a mapped network drive or from a local drive.  Just launching either `.bat` file appears to work fine (not that error, at least)

**Comment by dscho** [comment]
Hopefully this issue won't be a problem anymore, as [Git for Windows 2.x](http://git-for-windows.github.io/) adjusts the DLL ranges automatically as part of the installation process. Besides, the 64-bit version should be immune against this issue.

If not, please feel free to [contribute a new report](http://git-for-windows.github.io/#contribute), as Git for Windows 1.x was superseded by 2.x (and moved to a new org).
