### ISSUE TITLE
Feature: Use Git with remote Mercurial repo

### ISSUE THREAD

**Issue by jondo** [msysgit/git#241]
Reading your [Guide to git-remote-hg](https://github.com/msysgit/msysgit/wiki/Guide-to-git-remote-hg), it seems that there are still some issues until this functionality can be provided, but let me still create this tracker entry.

**Comment by sschuberth** [comment]
Our version of git-remote-hg has been discontinued. Please use [these remote helpers](https://github.com/git/git/tree/master/contrib/remote-helpers) instead.
