### ISSUE TITLE
[reopen] Inverted Commit Issues with Git merge --squash

### ISSUE THREAD

**Issue by hach-que** [msysgit/git#242]
We are still being impacted by https://github.com/msysgit/git/issues/120 (I can't find any way to reopen this issue).

This on average occurs about once a month in a repo with 30-40 developers actively.  This still occurs with at least Git 1.9.0.

The theory posted in the previous issue was "I suspect further, that it is a problem with the file system and could imagine that it is due to the time stamps being written using sub-second precision and subsequent inconsistent comparisons.", but (at least on our side), we have no way to verify if this is the case.

**Comment by dscho** [comment]
I am just assuming that it is fixed by [Git for Windows 2.x](http://git-for-windows.github.io/) -- or that there is not enough interest to pursue a resolution.
