### ISSUE TITLE
Pull fails in symlinked submodule on Windows

### ISSUE THREAD

**Issue by euclio** [msysgit/git#247]
Steps to reproduce:

1. Open Administrator command prompt.

        mkdir repo
        cd repo
        git init
        mkdir dir
        cd dir
        git submodule add <some arbitrary git repo> submodule
        cd ..
        mklink /D link dir\submodule
        cd link
        git pull origin master

2. Expected behavior: The submodule is updated to origin/master.
3. Actual behavior: Command fails, outputs

        fatal: Not a git repository: ../../.git/modules/dir/submodule

**Comment by dscho** [comment]
Symlink support was finally merged into [Git for Windows 2.x](http://git-for-windows.github.io/); Please note that you will have to activate the support specifically using `core.symlinks`:

```sh
git clone -c core.symlinks=true <URL>
```
