### ISSUE TITLE
Git GUI: 'Stage line/hunk for commit' initiates "Refreshing file status" (full rescan instead of just file rescan)

### ISSUE THREAD

**Issue by kju** [msysgit/git#255]
Git (version 1.9.4-preview20140815)

Observed:
It seems to rescan the whole repository for changes.

Expected:
It should only rescan the selected file.

Note: The same way it does, if you click in the left pane on files one by one.

Reproduction:
1. Have a repository with a large number of files with considerable size, so that scanning the repro takes a few seconds. (test via F5 key)
2. Have some non committed changes in the repo.
3. Open git gui.
4. Select a file with non committed changes.
5. Use right mouse button -> Stage line/hunk for commit

Notice how it takes a while for the screen to update as it rescans the whole repo instead of just the file.

**Comment by dscho** [comment]
Could you please verify whether that is still an issue with [Git for Windows 2.x](http://git-for-windows.github.io/) and follow the instructions in the *Contribute* section of its home page if the bug still persists? Thank you.
