### ISSUE TITLE
git stash list slow

### ISSUE THREAD

**Issue by elentirmo** [msysgit/git#259]
`git stash list` takes about 2 seconds when run from the Git Bash shell, in a newly created repository without any stashes.

This causes SublimeGit to be very slow on Windows, see https://github.com/SublimeGit/SublimeGit/issues/137.

Environment:
* Git-1.9.4-preview20140929
* Core i5, 8GB
* Windows 7 Pro, 64-bit English

**Comment by codejanovic** [comment]
my problems are gone with the latest version (2.5.0)

**Comment by dscho** [comment]
@codejanovic Thank you for testing, and I appreciate very much that you reported back.
