### ISSUE TITLE
Blame showing all lines as NCY

### ISSUE THREAD

**Issue by frogonwheels** [msysgit/git#260]
When doing a git blame (current master 87681137d9a1 )  with core.eol unset (native) and autocrlf=true,  the entire file is always under 'work NCY'.  

I suspect that there's a crlf translation issue here.  This happens in git gui blame as well as git blame (which I use via fugitive.vim).

**Comment by dscho** [comment]
@frogonwheels would you terribly mind switching to [Git for Windows 2.x' SDK](http://git-for-windows.github.io/#download-sdk), rebase your branch, and open a Pull Request? Even if you think there is more work to be done; in that case, at least others can see your current state and help out.
