### ISSUE TITLE
core.worktree

### ISSUE THREAD

**Issue by Keepun** [msysgit/git#270]
core.worktree sets the path to the --git-dir :(

In 1.9.2-preview20140411 setting works, but the files will not open.

**Comment by dscho** [comment]
@Keepun I missed that you updated your very terse explanation. So now it looks as if your problem might be solved by extending

```tcl
if {$_gitdir eq "."} {
   set _gitdir [pwd]
}
```

to

```tcl
if {$_gitdir eq "."} {
   set _gitdir [pwd]
} elseif ($_gitdir eq .git) {
   set _gitdir [pwd]/.git
}
```

If that fixes your problem, please report back and I will integrate the patch into [Git for Windows 2.x](http://git-for-windows.github.io/).
