### ISSUE TITLE
Trying to use git send-email --smtp-encryption=ssl, getting a missing SSL.pm error

### ISSUE THREAD

**Issue by gkodinov** [msysgit/git#271]
Hello,

I'm trying to use git on windows to send email to an SSL enabled SMTP server. 
I'm doing (in git bash) :
$ git send-email --smtp-server=<some server> --smtp-encryption=ssl --smtp-user=<some_user> --smtp-debug=1 --envelope-sender=<some email> --to=<some email>  --compose <some diff>

And I'm getting:
Can't locate Net/SMTP/SSL.pm in @INC (@INC contains: /lib /usr/lib/perl5/5.8.8/msys /usr/lib/perl5/5.8.8 /usr/lib/perl5/site_perl/5.8.8/msys /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl .) at C:\Program Files (x86)\Git/libexec/git-core\git-send-email line 1217, <FIN> line 1.

How do I add SSL.pm ? Is this something I can actually do ?

**Comment by dscho** [comment]
@gkodinov [Git for Windows 2.x](http://git-for-windows.github.io/) ships with `Net/SMTP/SSL.pm`. Would you please test with the new version that supersedes Git for Windows 1.x?

**Comment by gkodinov** [comment]
Yep, I can confirm it works now.
