### ISSUE TITLE
agent forwarding fails on update from Git-1.9.4-preview20140611 to Git-1.9.4-preview20140815

### ISSUE THREAD

**Issue by brendandc** [msysgit/git#275]
I use agent forwarding, and connections my AWS servers bounce through an intermediate server.

Basically, the setup works in `Git-1.9.4-preview20140611` but as soon as I install `Git-1.9.4-preview20140815`. Note: it also fails on the latest version: `Git-1.9.4-preview20140929`.

I am using Windows7, not sure if there any any other relevant details, but I am happy to provide them.

Providing my `.ssh/config` file with changed server names to help clarify the situation.

```
User brendandc

ForwardAgent yes

Host intermediary
      HostName intermediary.example.org

Host *.example.org
     ProxyCommand ssh intermediary nc %h %p
```

And then I connect in the git bash terminal with:
`ssh server-1.example.org`

**Comment by dscho** [comment]
I'll just assume that switching to [Git for Windows 2.x](http://git-for-windows.github.io/) solved the problem.
