### ISSUE TITLE
msysgit sh.exe is slow and shows errors in event log

### ISSUE THREAD

**Issue by johnkors** [msysgit/git#277]
I get these errors in the Windows Event log on Windows 8.1 using msysgit through cmder. The bundled version of Msysgit is

"Git Release Notes (Git-1.9.4-preview20140611)
Last update: 11 June 2014"

```
Faulting application name: sh.exe, version: 0.0.0.0, time stamp: 0x5399b4ca
Faulting module name: SYSFER.DLL, version: 12.1.5337.5000, time stamp: 0x5413ca74
Exception code: 0xc0000005
Fault offset: 0x00029591
Faulting process id: 0x20ec
Faulting application start time: 0x01cffe584df927ff
Faulting application path: C:\ProgramData\cmder\vendor\msysgit\bin\sh.exe
Faulting module path: C:\windows\SYSTEM32\SYSFER.DLL
Report Id: 8eb05100-6a4b-11e4-8279-3c77e6ec2549
Faulting package full name: 
Faulting package-relative application ID:
```
SYSFER.dll is related to Symantec anti-virus software it seems.

Every git pull request is really slow (up to a minute) on small git repos, and hangs on sh.exe (monitored through Process Explorer).

The same sluggishness and sh.exe also occurs when I use GitHub for Windows and that bundled msysgit version.

Any recommended ways of dealing with this if known?

**Comment by dscho** [comment]
Please test again with [Git for Windows 2.x](http://git-for-windows.github.io/) (which runs `rebase.exe` as part of its installation procedure). If you still encounter the issue, please [open a new ticket](http://git-for-windows.github.io/#contribute) because Git for Windows 1.x was retired.
