### ISSUE TITLE
Windows install errors

### ISSUE THREAD

**Issue by rswindell** [msysgit/git#280]
This is my first time installing msysgit, which I pulled down today and executed from https://github.com/msysgit/msysgit/releases/download/Git-1.9.4-preview20140929/msysGit-netinstall-1.9.4-preview20140929.exe
After the length install/build process, I was resented with a MINGW32:/git window with the following errors (or warnings):

-------------------------
Hello, dear Git developer.

This is a minimal MSYS environment to work on Git.

You are in the git working tree, and all is ready for you to hack.

Welcome to msysGit

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
Run '/share/msysGit/add-shortcut.tcl' to add a shortcut to msysGit.
sh.exe": /tools/bin/common.profile: No such file or directory
sh.exe": stty: command not found
sh.exe": stty: command not found
sh.exe": logname: command not found
sh.exe": w: command not found
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.

**Comment by dscho** [comment]
Silence is good. Silence means the bug was resolved. Or so I want to believe. Not much evidence to the contrary, at least :stuck_out_tongue_winking_eye:
