### ISSUE TITLE
using Windows Authentication fails for version > 1.8.1.2-preview20130201

### ISSUE THREAD

**Issue by SoonDead** [msysgit/git#282]
We have been using a Bonobo Git server internally which is configured to use Windows Authentication. This means that the IIS serving urls like `http://git.local/Project.git/` is configured to use Windows Authentication as well.

For a while now we are able to use our Active Directory accounts to simply authenticate through IIS in Git Bash. This is convenient.

With version 1.8.1.2-preview20130201 the process worked seamlessly. No further configuration was needed.

After someone updated to a newer msysgit version he was unable to authenticate to the server. The request didn't get through the Windows Authentication configured through IIS, it seemed it did not try to complete the challenge at all.

So we reverted to the old version and have been postponing the update since, but now it has already been 1.5 years, so an update may be in order.

I'm not sure what else should I report about the process, what logs/messages should I include in this bug report, but I'm willing to provide any information available.

This was reported on the old bug tracker (back when the project was on google code), but I was not following the life-cycle of the ticket.

**Comment by alexchandel** [comment]
This issue forces Bonobo-Git-Server to employ an [inconvenient workaround](https://github.com/jakubgarfield/Bonobo-Git-Server/issues/167) for Windows authentication. :+1:

**Comment by dscho** [comment]
@SoonDead @alexchandel please try again with [Git for Windows 2.x](http://git-for-windows.github.io/). If the problem persists, we will need an easy way to reproduce. Once you have that, please [open a new ticket](http://git-for-windows.github.io/#contribute) there.

**Comment by SoonDead** [comment]
Git for Windows 2.5 seems to be working fine with Windows Authentication.

Thanks for fixing this.

**Comment by dscho** [comment]
Thanks for testing!
