### ISSUE TITLE
git gui pull button

### ISSUE THREAD

**Issue by cookacounty** [msysgit/git#284]
Could a pull button be added to the gui that then pops up a form to choose which branch to pull?
Constantly doing fetch+merge is inefficient and the only alternative is to open bash which is just as slow.

**Comment by patthoyts** [comment]
I'll look into doing this. Its a good idea.

**Comment by dscho** [comment]
@patthoyts did you ever get anywhere with this ticket, or can I close it?

**Comment by dscho** [comment]
Let's reopen it in https://github.com/git-for-windows/git/issues when (or if) this is still being worked on.
