### ISSUE TITLE
Git over samba - unable to write sha1 filename 

### ISSUE THREAD

**Issue by javin158** [msysgit/git#286]
I use msygit 1.8.4 on windows xp, and when I add a new file over samba and commit  to git server,  the error occurs:
error: unable to write sha1 filename .git/objects/f5/a13c670d8781cf73e74f19a62ae3bce885e8ee: Permission denied
error: Error building trees

I have root permission on the samba and I can write file over samba. so I don't understand why 'Permission denied' occurs.  Actually， git on Cygwin works fine over samba.

**Comment by dscho** [comment]
Please try again with [Git for Windows 2.x](http://git-for-windows.github.io/). If the problem persists, please ask at the forum/mailing list https://groups.google.com/forum/#!forum/git-for-windows (you might want to follow the advice given in https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines to give others a better chance to reproduce and help).
