### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by GabrielJMJ** [msysgit/git#290]
After bug warning I downloaded git for Windows. Both [here](http://git-scm.com/downloads) and [here](http://msysgit.github.io/) Windows (7) throws an error saying that I don't have permissions to install it. I have an older version from Git for Windows and I didn't have problems to install it. What can I do? Sorry for this be an nood doubt.

Chrome error:
![Chrome error](http://i.gyazo.com/a1a6a24e3be1f401b5345377d500c26b.png)
you can not save it because of insufficient permissions. Save elsewhere.

If it downloads, when I click to install throw the same error and the file is deleted.

Thank you.

**Comment by Zertz** [comment]
This also happened on both of my Windows 8.1 64-bit PC's. When I run the file, the cursor briefly displays a loading animation and then nothing happens for ~10 minutes. Everything seems fine after that initial hickup.

**Comment by TheOleg** [comment]
Same problem as above.

Is there link for older verison?

**Comment by ametad** [comment]
This problem occurs also on my system (Win8.1) today with Git-1.9.5-preview20150319.exe. No installer screen appears, not even after 15+ minutes. Also not with administrative rights or after reboot(s).

**Comment by ametad** [comment]
WAAAAH! 
This is weird... I have given the command to execute the installer file about ~30 minutes ago... and all of a sudden the screen does appear! I can install now correctly.
I think this has to do with Windows Defender / Antimalware Service Executable, for it did consume about 10%cpu power from the moment I gave the command to execute.

**Comment by dscho** [comment]
Hmm. This issue really wants somebody who can reproduce to investigate in detail what is happening. Maybe Windows Defender decides to unpack the entire contents before it lets the installer start? It would still be insanely slow if it did that.

So please, somebody who noticed this issue on their computer: download the net installer via https://msysgit.github.io/#download-msysgit, run it (it will build Git), then build an installer via `/share/WinGit/release.sh mytest`. Once that built the installer, try to run it to see whether it still hangs. If it does, the next thing would be to find out whether the *installer* is actually already running, or whether some antivirus prevents it from doing its job swiftly, most likely by editing `/share/WinGit/install.iss` to print out some debug message right at the start.

Sorry that I cannot help more without a way to reproduce. But look at it this way: this is a perfect opportunity to thank for this Open Source software by helping it getting even better.

**Comment by prust** [comment]
I just ran into this as well (installer hangs on Win7). I confirmed what @ametad found: the culprit is the Windows antivirus software's Real-Time protection. I discovered that this was maxing out a core on my machine (had to "Show processes from all users" to see that). I did a full machine restart, which killed the process, then turned off the Real-Time protection, then the git installer came up quickly.

**Comment by dscho** [comment]
Maybe this is no longer an issue, now that Git for Windows 1.x has been retired, and [Git for Windows 2.x](https://git-for-windows.github.io/)'s installers are signed?

In any case, I am closing this ticket. Please open a new one [in the new org](https://github.com/git-for-windows) if the bug persists even with 2.x.
