### ISSUE TITLE
Git with Python support?

### ISSUE THREAD

**Issue by TurkeyMan** [msysgit/git#295]
Is it possible to build msysgit with python support, where support is optional, depending if the user has python installed or not?

'git p4' depends on python, and since windows is a very popular p4 platform, it would be super useful if we could attach git to our workflow.

**Comment by terrehbyte** [comment]
My teammates and I got 'git p4' working flawlessly on Windows after taking a look at an [issue on msysgit](https://github.com/msysgit/msysgit/issues/108) that also asked for support for it on Windows.

We did the following:
1. Install [Git for Windows](https://msysgit.github.io/).
2. Installed the latest version of [Python 2](https://www.python.org/downloads/) (2.7.9 at the time). Make sure you add python to your PATH environment variable.
3. Replaced the placeholder git-p4 script with the [actual one](https://github.com/git/git/blob/master/git-p4.py). For me, this was at ```C:\Program Files (x86)\Git\libexec\git-core\git-p4```.

It should be ready to use after following the above steps.

**Comment by dscho** [comment]
@terrehbyte unfortunately, that does not fit in the maintenance scheme chosen for Git for Windows (neither msysGit-based 1.x nor MSys2-based 2.x). If you are interested enough to resolve this issue, please work with me by opening a Pull Request with [Git for Windows 2.x](http://git-for-windows.github.io/).
