### ISSUE TITLE
git rebase command does not do partial auto-completion

### ISSUE THREAD

**Issue by najumancheril** [msysgit/git#297]
I recently upgraded to 1.9.5.msysgit.0.

When I now type "git rebase ori" followed by TAB, it asks me whether I want display all 600+ possibilities, which is the number of branches at the origin repository. Previous versions of msysgit would auto-complete up to "git rebase origin" and then let me type in the branch name that I was interested in.

**Comment by dscho** [comment]
Does this persist? I cannot reproduce. In any case, please switch to [Git for Windows 2.x](http://git-for-windows.github.io/); Git for Windows 1.x was retired a week ago.

**Comment by najumancheril** [comment]
This problem has been fixed in 2.x. Thanks!
