### ISSUE TITLE
Unable to use git+svn perl and libsvn error

### ISSUE THREAD

**Issue by avdyk** [msysgit/git#300]
Hi,

I've just upgrade and I'm no more able to use git+svn!

C:\Program Files (x86)\Git\bin\perl.exe: *** unable to remap C:\Program Files (x
86)\Git\bin\libsvn_wc-1-0.dll to same address as parent -- 0x6F1C0000

Am I the only one?

Does some one have a fix I can (easily) apply?

Many thanks for your work,

**Comment by dscho** [comment]
Sounds like you need to use `rebase.exe` (see the explanation of https://github.com/msysgit/msysgit/commit/71f78b1816e3ff841f737672d43af36d099cb26f even if it describes a slightly different problem – most likely with the same solution, though).

**Comment by avdyk** [comment]
I tried:
$ rebase.exe -b 0x67000000 bin/msys-1.0.dll
ReBaseImage (bin/msys-1.0.dll) failed with last error = 6

and
$ rebase.exe -b 0x6F1C0000 bin/msys-1.0.dll
ReBaseImage (bin/msys-1.0.dll) failed with last error = 6

Doesn't work for me :/

**Comment by dscho** [comment]
@avdyk the `.dll` your error message was complaining about was *not* `bin/msys-1.0.dll`. Besides, please note that you can only rebase the entry point address of a `.dll` that is *not* currently in use.

**Comment by avdyk** [comment]
Here is the error:
$ git svn rebase
C:\Program Files (x86)\Git\bin\perl.exe: *** unable to remap C:\Program Files (x86)\Git\bin\libsvn_wc-1-0.dll to same address as parent -- 0x6F1C0000
      0 [main] perl.exe" 8324 sync_with_child: child 8984(0x1AC) died before initialization with status code 0x1

but I don't know how to use the rebase.exe application. Any idea?

**Comment by avdyk** [comment]
I re-installed 1.9.2-preview20140411 'cause the 1.9.5-preview20141217 is not usable for me and I can't fix it. I'll be glad to upgrade when the problem will be solved.

Cheers and thanks for your work, I use your tool everyday!

**Comment by dscho** [comment]
@avdyk when you have the time, please test whether the latest release candidate of [Git for Windows 2.x](https://git-for-windows.github.io/) fixes this. Its installer automatically calls `rebase.exe` in the way I suggested.

**Comment by dscho** [comment]
Closing this ticket in favor of Git for Windows 2.x (which is now officially released). Get it e.g. from https://git-scm.com/...

**Comment by avdyk** [comment]
I'm sorry, I don't use Windows any more ;-)
