### ISSUE TITLE
Newer version of bash

### ISSUE THREAD

**Issue by martinheidegger** [msysgit/git#301]
If I am not mistaken msysgit comes with a old bash version "3.1.x". Would it be possible to update this to "4.x"?

**Comment by sschuberth** [comment]
Yeah, I'd love to have Bash 4, too. But unfortunately it's quite involving to build it on MSYS ourselves. The easiest for us would be if it were available upstream in MSYS, so please feel free to [report an issue over there](https://sourceforge.net/p/mingw/bugs/).

**Comment by t-b** [comment]
IIRC msys itself is too old for bash 4. Obviously one could then switch to MSYS2...

**Comment by sschuberth** [comment]
> IIRC msys itself is too old for bash 4.

Interesting. Can you elaborate / do you have a source for that?

**Comment by dscho** [comment]
We switched to MSys2, and [Git for Windows 2.x](http://git-for-windows.github.io/) is out, superseding Git for Windows 1.x.

**Comment by martinheidegger** [comment]
:+1:
