### ISSUE TITLE
Excess characters in Git Bash (\E[1m etc)

### ISSUE THREAD

**Issue by lxatong** [msysgit/git#305]
Hello.
I have installed Git for Windows (Git-1.9.5-preview20141217.exe) and I have installed Arcanist (a command-line interface to Phabricator which uses PHP - https://secure.phabricator.com/book/phabricator/article/arcanist_windows/) on Windows XP Pro SP3 RU.
When I run Arcanist from Git Bash in an output window there are excess characters. When I run Arcanist from cmd.exe - everything is OK.
I tried different settings of installation of Git for Windows, and also I tried to change a font in properties of the Git bash window after installation - everything ineffectually.
![git bash](https://cloud.githubusercontent.com/assets/10601454/5807248/f7541468-a029-11e4-89f2-18bdbe998fc5.PNG)

**Comment by sschuberth** [comment]
Seems to be related to https://secure.phabricator.com/T5724.

**Comment by dscho** [comment]
@lxatong does this bug persist with [Git for Windows 2.x](http://git-for-windows.github.io/)? If yes, please contribute a new bug report in the new org, [as per our guidelines](http://git-for-windows.github.io/#contribute). Thank you.
