### ISSUE TITLE
Cannot connect to ipv6 server via git bash

### ISSUE THREAD

**Issue by jugmac00** [msysgit/git#306]
I have the very same error messages as outlined in 
https://github.com/msysgit/git/issues/131
which was unfortunately closed.

We are about to move our linux box to a new provider, which others only ipv6 connection. When I try to connect either via ssh or git clone I get the same error messages as in aboven mentioned issue.

Putty works, mobaxterm work, but I would really like to continue to use git bash. What are the plans in future? 

When t-b said, use plink or copssh in above mentioned issue- did he mean as standalone alternative or as plugin to git-bash? If latter one, who to do that?

**Comment by t-b** [comment]
Dup
