### ISSUE TITLE
windows 7 file explorer crashes after mkdir via git bash

### ISSUE THREAD

**Issue by Daniel-Hug** [msysgit/git#308]
From http://superuser.com/q/863941/75775:

My environment:

 - Windows 7
 - Git v1.9.0

Steps to reproduce my problem:

 1. open a folder in windows explorer
 2. right click in that folder and select "Git Bash"
 3. execute: "mkdir test" in the git bash window that pops up
 4. windows explorer stops responding

If I `cd` into the folder instead of going directly there with the right click method, explorer won't crash.

**Comment by dscho** [comment]
As per http://superuser.com/a/865533 this was fixed in Git Cheetah as shipped with 1.9.2. Besides, with [Git for Windows 2.x](http://git-for-windows.github.io/), we do not even support Git Cheetah anymore. Closing.
