### ISSUE TITLE
Rebase against a reset branch fails

### ISSUE THREAD

**Issue by twsouthwick** [msysgit/git#313]
I keep running into the following issue.  The scenario is:

*I start working a feature on master without realizing it.  I branch from my latest commit, and then want to reset master to be aligned with origin/master.  All is fine, until I want to rebase my new branch against master.  The rebase interactive prompt tells me that it is a noop and does not list any commits.*

I could not repro it on an Ubuntu machine, so I'm assuming it's Windows specific:

1. Create a new git repo

	git init

2. Create a file and make a commit

	echo "something" > test.txt
	git add test.txt
	git commit -m "First commit"

3. Make a change to the file and commit

	echo "something2" > test.txt
	git add test.txt
	git commit -m "Second commit"

4. Create a new branch

	git branch test-branch

5. Reset `master` to first commit

	git reset HEAD^ --hard

6. Go to `test-branch` and attempt to do an interactive rebase against `master`

	git checkout test-branch
	git rebase master -i

The output is:

	noop

	# Rebase 02c80a3..02c80a3 onto dc9771b
	#
	# Commands:
	#  p, pick = use commit
	#  r, reword = use commit, but edit the commit message
	#  e, edit = use commit, but stop for amending
	#  s, squash = use commit, but meld into previous commit
	#  f, fixup = like "squash", but discard this commit's log message
	#  x, exec = run command (the rest of the line) using shell
	#
	# These lines can be re-ordered; they are executed from top to bottom.
	#
	# If you remove a line here THAT COMMIT WILL BE LOST.
	#
	# However, if you remove everything, the rebase will be aborted.
	#
	# Note that empty commits are commented out

When I expected something like (which is what I see in Ubuntu):

	pick 02c80a3 Second commit	
	
	# Rebase dc9771b..02c80a3 onto dc9771b
	#
	# Commands:
	#  p, pick = use commit
	#  r, reword = use commit, but edit the commit message
	#  e, edit = use commit, but stop for amending
	#  s, squash = use commit, but meld into previous commit
	#  f, fixup = like "squash", but discard this commit's log message
	#  x, exec = run command (the rest of the line) using shell
	#
	# These lines can be re-ordered; they are executed from top to bottom.
	#
	# If you remove a line here THAT COMMIT WILL BE LOST.
	#
	# However, if you remove everything, the rebase will be aborted.
	#
	# Note that empty commits are commented out

I'm currently running git version 1.9.5.msysgit.0; however I have seen this behavior for the past year since I started using git

**Comment by sschuberth** [comment]
But this really *is* a noop. In your example, step 6, `test-branch` is exactly one commit head of `master`. In other words, `master`could be fast-forwarded to `test-branch`, as `master` is a strict sub-set of `test-branch`.

And then you're telling Git to rebase that one commit which `test-branch` is ahead of `master` onto `master`, which is exactly what `test-branch` already is.

If you see different behavior on Ubuntu, that's almost certainly because on that platform `master` has gotten new commits in between that are not in `test-branch`.

**Comment by twsouthwick** [comment]
This may be misunderstanding on my part of an interactive rebase, but it seems like this shouldn't be a noop, as the interactive rebase should allow reordering of commits. Also, there are no new commits on master on the Ubuntu version - the steps I followed on each machine were identical.

**Comment by t-b** [comment]
@twsouthwick Do you have the same version of git on linux and windows? And can you check with 1.9.5 on linux?

**Comment by sschuberth** [comment]
> This may be misunderstanding on my part of an interactive rebase, but it seems like this shouldn't be a noop, as the interactive rebase should allow reordering of commits.

You're right, I spoke too early and missed that it's an *interactive* rebase. I just followed our steps with `git version 1.9.5.msysgit.0` which works as expected for me, I see `pick 1ec42ba Second commit` in the editor.

**Comment by twsouthwick** [comment]
I tried it on 1.9.5 on Linux and I get the expected output. Previously, I was using 1.9.1 on Linux.

**Comment by twsouthwick** [comment]
Hmm... it's working now, as @sschuberth said.  I used to do the following:
	
	git checkout test-branch
	git branch -u master
	git rebase -i
	
instead of what I put on step 6:

	git checkout test-branch
	git rebase master -i
	
Setting the upstream branch causes the noop.  I must have switched the commands I used at some point while trying to diagnose the issue.  Why would setting the upstream branch give a different result than passing the branch name to rebase?  Git on Linux gives the noop with these commands as well.

**Comment by sschuberth** [comment]
According to [the docs](http://git-scm.com/docs/git-rebase.html), "If &lt;upstream&gt; is not specified [...] the --fork-point option is assumed". However, "When --fork-point is active, fork_point will be used instead of &lt;upstream&gt; to calculate the set of commits to rebase". In your case the fork-point is determined by `git merge-base --fork-point master test-branch`, which points to "Second commit", resulting in a noop when doing the rebase. So it basically boils down to different defaults when omitting arguments.

**Comment by twsouthwick** [comment]
Interesting!  Thanks for the help.  I'll go ahead and close this issue since it seems to work as it should (just not how I was expecting)
