### ISSUE TITLE
Could not open a connection to your authentication agent.

### ISSUE THREAD

**Issue by SimpleExpress** [msysgit/git#315]
On Windows 7 home basic, I can't run ssh-add as it always says "Could not open a connection to your authentication agent.". I have tried some suggestions (like this post http://stackoverflow.com/questions/17846529/could-not-open-a-connection-to-your-authentication-agent) but all were failed. Will you give suggestions, thanks a lot.

**Comment by t-b** [comment]
I do
- open Git Bash
- Enter `eval $(ssh-agent)`
- ssh-add $pathToPrivateKey

and it works here.

**Comment by dscho** [comment]
@SimpleExpress if the problem persists with [Git for Windows 2.x](http://git-for-windows.github.io/), please open a new bug report there, according to our [issue reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines).
