### ISSUE TITLE
The git.exe executable opens up a command-line window each time it is launched

### ISSUE THREAD

**Issue by Polyethylene** [msysgit/git#316]
The git.exe executable opens up a command-line window each time it is launched, before closing itself. The output gets rendered in the new window, then the command is restarted in the current console.

The problem is not terminal-specific (tested on cmd.exe via msys.bat and in the IntelliJ WebStorm terminal), and only happens with git.exe (not with git-add.exe for instance).

Win 8.1 x64, msysGit netinstall 1.9.5 (preview 20141217)

**Comment by dscho** [comment]
Are you sure you are calling the `git.exe` contained in the `bin/` subdirectory, *not* the one from the `cmd/` subdirectory?

**Comment by Polyethylene** [comment]
Yes, I'm positive. It's the git.exe in msysgit/bin/

**Comment by mmcintyre123** [comment]
This is so annoying as the sublime package GitGutter calls git.exe when saving files to run git diff I think, and whenever I save now the separate cli window flashes (opens then closes).  Sometimes it gets pretty slow too (cache build up?), which makes it harder to work.  I'm on Windows 7.  Any solution would be much appreciated!  See also https://github.com/jisaacks/GitGutter/issues/246

**Comment by dscho** [comment]
I fear it is the same issue with [Git for Windows 2.x](https://git-for-windows.github.io/). Nevertheless, Git for Windows 1.x has beeb retired.

So: would you terribly mind to test again with the new version and [open a new bug report](http://git-for-windows.github.io/#contribute) if the bug persists? I promise to take better care there, especially if I get an [MCVE](http://stackoverflow.com/help/mcve).

**Comment by dscho** [comment]
In any case, I close this ticket because if we need any fix, it will be in the new Git for Windows.

**Comment by mmcintyre123** [comment]
Hi there!  No problem I'll open a new ticket there.  Thanks!
