### ISSUE TITLE
Git cannot remove non-empty folders

### ISSUE THREAD

**Issue by pal1000** [msysgit/git#319]
This mainly happens when you commit submodule removals.
Solution: call RD with /S /Q arguments in order to succeed.

**Comment by dscho** [comment]
It would be a serious bug if Git removed directories that are not empty. Please note that Git will try to remove files it knows about when you call, say, `git rm -r`; Therefore, if the directory still has files in them, Git will simply refuse to let the user shoot into her knee by removing files that might still be needed, but that are not tracked at all.
