### ISSUE TITLE
git svn. libsvn_ra_local-1-0.dll to same address as parent -- 0x6E050000

### ISSUE THREAD

**Issue by turbanoff** [msysgit/git#329]
Recently (perhaps after windows update) my git start to show errors:

    D:\Projects\pumper>git svn fetch
    C:\Program Files (x86)\Git\bin\perl.exe: *** unable to remap C:\Program Files (x86)\Git\bin\libsvn_ra_local-1-0.dll to same address as parent -- 0x6E050000
          0 [main] perl.exe" 2540 sync_with_child: child 7424(0x2A4) died before initialization with status code 0x1
        317 [main] perl.exe" 2540 sync_with_child: *** child state child loading dlls
    C:\Program Files (x86)\Git\bin\perl.exe: *** unable to remap C:\Program Files (x86)\Git\bin\libsvn_ra_local-1-0.dll to same address as parent -- 0x6E050000
    5076408 [main] perl.exe" 2540 sync_with_child: child 1792(0x2BC) died before initialization with status code 0x1
    5076823 [main] perl.exe" 2540 sync_with_child: *** child state child loading dlls]
    ...

**Comment by dscho** [comment]
Hi Andrej,

On 2015-03-16 11:26, Турбанов Андрей wrote:
> Recently (perhaps after windows update) my git start to show errors:
> 
>     D:\Projects\pumper>git svn fetch
>     C:\Program Files (x86)\Git\bin\perl.exe: *** unable to remap
> C:\Program Files (x86)\Git\bin\libsvn_ra_local-1-0.dll to same address
> as parent -- 0x6E050000
>           0 [main] perl.exe" 2540 sync_with_child: child 7424(0x2A4)
> died before initialization with status code 0x1
>         317 [main] perl.exe" 2540 sync_with_child: *** child state
> child loading dlls
>     C:\Program Files (x86)\Git\bin\perl.exe: *** unable to remap
> C:\Program Files (x86)\Git\bin\libsvn_ra_local-1-0.dll to same address
> as parent -- 0x6E050000
>     5076408 [main] perl.exe" 2540 sync_with_child: child 1792(0x2BC)
> died before initialization with status code 0x1
>     5076823 [main] perl.exe" 2540 sync_with_child: *** child state
> child loading dlls]
>     ...

https://github.com/msysgit/msysgit/commit/71f78b1816e3ff841f737672d43af36d099cb26f has an explanation. If you find that information useful, it would be much appreciated if you could edit the Wiki at https://github.com/msysgit/msysgit/wiki to offer this information in a way that is easier to find.

Thank you.

**Comment by dscho** [comment]
I would have appreciated feedback.
