### ISSUE TITLE
Git 2.x for Windows

### ISSUE THREAD

**Issue by asesh** [msysgit/git#331]
If you are a Windows user then git-scm.com still doesn't let us download the latest version of git. Instead they are still stuck with older versions of git. Why? it's been ages git 2.x was released

**Comment by t-b** [comment]
We are switching the underlying SDK of git for windows. And that takes time. We have no ETA when its ready.

**Comment by dscho** [comment]
@asesh You could find out why it takes so long by getting involved in the project. This would also have the benefit for you, personally, that you get faster what you want.
