### ISSUE TITLE
Push to gerrit via https is broken

### ISSUE THREAD

**Issue by orgads** [msysgit/git#332]
Trying to push to gerrit repository (codereview.qt-project.org, but also other gerrit repos on https), I'm receiving 403 error. Curl log in https://paste.kde.org/pcvt1lado

Git version is 1.9.5.msysgit.1. Windows 7.

It worked fine with 1.9.5.msysgit.0.

**Comment by dscho** [comment]
Please read and follow [this advice](https://github.com/msysgit/msysgit/wiki#issue-reporting-guidelines) to improve your bug report substantially.

**Comment by orgads** [comment]
Sorry. Fixed my report.

**Comment by dscho** [comment]
> Fixed my report.

As far as I am concerned, this is the (still unfixed) report: https://github.com/msysgit/git/issues/332#issue-63743791

**Comment by orgads** [comment]
I added git version, the problem seems clear to me. What is missing?

**Comment by orgads** [comment]
A successful push with 1.9.5.msysgit.0 is here: https://paste.kde.org/poh3tf2j3.

Pushing to github via https does work, so I guess only digest authentication which is used by gerrit is broken.

**Comment by t-b** [comment]
Looks like this was broken by the curl update to 7.41.0.

@orgads Can you create a minimal working example which reproduces the problem and works on my machine too?

**Comment by orgads** [comment]
* [Setup a Jira account](https://bugreports.qt.io/secure/Signup!default.jspa)
* Sign in to [qt-project gerrit](https://codereview.qt-project.org) with the same credentials.
* Open the [user settings -> HTTP Password](https://codereview.qt-project.org/#/settings/http-password)
* Click Generate Password
* Copy the generated password
* Edit ~/_netrc
* Add a line `machine codereview.qt-project.org login <username> password <generated password>`, then save
```
git clone https://codereview.qt-project.org/qt/qtrepotools
cd qtrepotools
git push
```

**Comment by t-b** [comment]
@orgads Hmm that is a bit too involved for me ATM.

In case you know how a C-compiler works have a try with the following:
- Download msysgit from [here](https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20150319/msysGit-netinstall-1.9.5-preview20150319.exe).
- Install it and let it compile git
- Execute msys.bat from the installation folder
- cd /src/curl
- Revert a87e1 and have a try with the previous curl version.
- Create a minimal working testcase (just code calling curl) and mail the curl devs [here](http://cool.haxx.se/mailman/listinfo/curl-users)
- Tell us here what you found out

**Comment by orgads** [comment]
Ok, to begin with, I created an account and have a minimal command that fails with 7.41 and succeeds with 7.30:

`curl -k --digest --user 'msysgit:54Y01sW1Y0Z+' https://codereview.qt-project.org/p/qt/qtrepotools/info/refs?service=git-receive-pack`

It doesn't reproduce on linux with self-built curl 7.41 (default flags).

**Comment by t-b** [comment]
@orgads Thanks for the recipe!

And indeed I get a 403.
I just tried our new git-for-windows sdk, [latest test release](https://github.com/git-for-windows/build-extra/releases/tag/net-installer-preview-1) and it works there.

So it might not be a curl problem after all.

**Comment by orgads** [comment]
Hi,

Any progress?

**Comment by dscho** [comment]
@orgads funny, I wanted to ask the same... Have you been able to verify @t-b's claim that it works with the latest test release?

**Comment by orgads** [comment]
Sorry, I didn't realize that @t-b was asking me to test it, as I did provide a very simple way for testing.

Anyway, I just tested with the test release and it doesn't reproduce.

**Comment by dscho** [comment]
> I just tested with the test release and it doesn't reproduce

So you mean that the upcoming Git for Windows 2.x has fixed this bug, yes?

I'll leave it to @t-b whether he wants to help you fix the bug in Git for Windows 1.x or instead close the ticket to focus on Git for Windows 2.x.

**Comment by orgads** [comment]
hmm... With latest 2.4.0 it reproduces... :(

**Comment by orgads** [comment]
It is fixed in curl master (not released yet), commit https://github.com/bagder/curl/commit/59f3f92ba6150e9a5a57f71b6e781802148916d0

**Comment by orgads** [comment]
Created PR: https://github.com/Alexpux/MINGW-packages/pull/614

**Comment by dscho** [comment]
@orgads would you agree that this ticket is addressed?

**Comment by orgads** [comment]
Sure
