### ISSUE TITLE
SVN bridge garbage collection fails with an error

### ISSUE THREAD

**Issue by kappa7194** [msysgit/git#336]
I'm using Git as a bridge to a Subversion repository, if I try to run the `git svn gc` command it fails with the error _"Compress::Zlib could not be found; unhandled.log files will not be compressed."_, it seems a PERL module is missing.

I'm using version `git version 1.9.4.msysgit.2` downloaded from http://git-scm.com/.

Let me know if you need additional information.

**Comment by dscho** [comment]
First of all, 1.9.4.msysgit.2 is pretty old by now. We had two 1.9.5 releases in the meantime.

Further, we are currently switching to a new development environment, with more up-to-date packages. How about giving it a try? Just download the appropriate [net installer](https://github.com/git-for-windows/build-extra/releases/tag/net-installer-preview-1), let it build Git, and then call `pacman -S subversion` to add the Subversion support. After that, `git svn` should work.

**Comment by kappa7194** [comment]
I've installed version `1.9.5.msysgit.1`, the problem persist.

I tried to look at https://github.com/git-for-windows/build-extra but I couldn't find any installation instruction. Do I only have to tun `setup-git-sdk.bat`? Do I have to uninstall version `1.9.5.msysgit.1` before? Does it require any manual dependency?

**Comment by dscho** [comment]
> I tried to look at https://github.com/git-for-windows/build-extra but I couldn't find any installation instruction.

Please have a look at the net installer: https://github.com/git-for-windows/build-extra/releases/tag/net-installer-preview-1

**Comment by kappa7194** [comment]
>Please have a look at the net installer: https://github.com/git-for-windows/build-extra/releases/tag/net-installer-preview-1

Yes I was talking about that, I downloaded `git-sdk-64-installer-preview.7z.exe` and was wondering if I only had to run the self-extracting archive.

Doing so the installation fails:

```
:: Synchronizing package databases...
 git-for-windows                                                                                  0.0   B  0.00B/s 00:00 [------------------------------------------------------------------------]   0%
 git-for-windows                                                                               1392.0   B  1359K/s 00:00 [########################################################################] 100%

error: failed retrieving file 'mingw32.db' from downloads.sourceforge.net : Connection timed out after 10000 milliseconds
error: failed to update mingw32 (download library error)
error: failed retrieving file 'mingw64.db' from downloads.sourceforge.net : Connection timed out after 10000 milliseconds
error: failed to update mingw64 (download library error)
error: failed retrieving file 'msys.db' from downloads.sourceforge.net : Connection timed out after 10000 milliseconds
error: failed to update msys (download library error)
error: failed to prepare transaction (could not find database)
warning: database file for 'mingw32' does not exist
warning: database file for 'mingw64' does not exist
warning: database file for 'msys' does not exist
error: target not found: pacman
warning: database file for 'mingw32' does not exist
warning: database file for 'mingw64' does not exist
warning: database file for 'msys' does not exist
:: There is 1 member in group base:
:: Repository git-for-windows
   1) msys2-runtime

Enter a selection (default=all):
error: target not found: python
error: target not found: less
error: target not found: openssh
error: target not found: patch
error: target not found: make
error: target not found: tar
error: target not found: diffutils
error: target not found: ca-certificates
error: target not found: perl-Error
error: target not found: perl
error: target not found: perl-Authen-SASL
error: target not found: perl-libwww
error: target not found: perl-MIME-tools
error: target not found: perl-Net-SMTP-SSL
error: target not found: perl-TermReadKey
error: target not found: mintty
error: target not found: mingw-w64-x86_64-toolchain
error: target not found: mingw-w64-x86_64-curl
error: target not found: mingw-w64-x86_64-expat
error: target not found: mingw-w64-x86_64-openssl
error: target not found: mingw-w64-x86_64-tcl
error: target not found: mingw-w64-x86_64-pcre
'mintty' is not recognized as an internal or external command,
operable program or batch file.
```

Maybe it has something to do with me being behind an HTTP proxy? (No, I can't disable it: we don't have direct internet connection, everything must go through the corporate proxy.)

**Comment by dscho** [comment]
> downloads.sourceforge.net : Connection timed out

Unfortunately, this is a known issue with SourceForge: some of these days it is less reliable than we would wish. Typically, it worked for me after I waited a couple of minutes.

FWIW the net installer that is about to be released tries to work around such failures.

**Comment by kappa7194** [comment]
I tried over a dozen times in the past five hours with no success.

I then managed to enable WiFi tethering on my mobile phone, disconnect the corporate network, and connect to the mobile phone hot-spot, I then launched the setup and it's currently downloading things.

So I think the installer doesn't work when behind a proxy. Would you like me to report the issue on https://github.com/git-for-windows/build-extra?

**Comment by dscho** [comment]
> I then managed to enable WiFi tethering on my mobile phone, disconnect the corporate network, and connect to the mobile phone hot-spot, I then launched the setup and it's currently downloading things.
> 
> So I think the installer doesn't work when behind a proxy.

Yes, that's the problem, you're absolutely correct!

> Would you like me to report the issue on https://github.com/git-for-windows/build-extra?

In the git-for-windows org, we only have one centralized bug tracker, to prevent confusion which bug tracker to use: https://github.com/git-for-windows/git/issues

I would be glad to work with you on resolving this issue.

**Comment by kappa7194** [comment]
Done, I opened issue https://github.com/git-for-windows/git/issues/46.

I also opened issue https://github.com/git-for-windows/git/issues/47 because later on the installer fails with a `command not found` error.

**Comment by dscho** [comment]
Thanks @kappa7194.
