### ISSUE TITLE
installer fails due to msgfmt?

### ISSUE THREAD

**Issue by kenjiuno** [msysgit/git#337]
I'm using TortoiseGit on Windows 8.1 (x64) Japanese ver.

`msysGit-netinstall-1.9.5-preview20150319.exe` fails to install.

Here is output from recent lines:
```
GITGUI_VERSION = 0.19.GITGUI
cp windows/git-gui.sh git-gui
    * new locations or Tcl/Tk interpreter
    GEN git-gui.tcl
    INDEX lib/
    MSGFMT    po/bg.msg 543 translated.
    MSGFMT    po/de.msg 520 translated.
    MSGFMT    po/el.msg 381 translated, 10 fuzzy.
    MSGFMT    po/fr.msg 520 translated.
    MSGFMT    po/hu.msg 514 translated.
    MSGFMT    po/it.msg 519 translated, 1 untranslated.
    MSGFMT    po/ja.msg 520 translated.
    MSGFMT    po/nb.msg 474 translated, 39 untranslated.
    MSGFMT po/pt_br.msg 520 translated.
    MSGFMT    po/ru.msg 516 translated, 4 untranslated.
    MSGFMT    po/sv.msg 521 translated.
    MSGFMT po/zh_cn.msg 366 translated, 8 fuzzy, 17 untranslated.
    SUBDIR gitk-git
    * new Tcl/Tk interpreter location
    GEN gitk-wish
Generating catalog po/bg.msg
msgfmt --statistics --tcl po/bg.po -l bg -d po/
302 ﾂﾌ|bZ[W.
make[1]: *** [po/bg.msg] Error 1
make: *** [all] Error 2


-------------------------
Hello, dear Git developer.

This is a minimal MSYS environment to work on Git.

Your build failed...  Please fix it, and give feedback on the Git list.

Welcome to msysGit


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
Run '/share/msysGit/add-shortcut.tcl' to add a shortcut to msysGit.

Sola@G45 /git (master)
$
```

`export LANG=C` helped to succeed following `make` and `make install` commands. However it doesn't complete the setup process?

I continue to get the following message after `make install`.

![still](https://cloud.githubusercontent.com/assets/5955540/6847325/030dcc1e-d409-11e4-8c23-6ea2cacd445a.png)

Any advice to complete the installation?

**Comment by sschuberth** [comment]
You probably do not want msysgit (which is the developer environment for working *on* Git itself), but Git for Windows (which is the end user environment to *use* Git, e.g. in conjunction with TortoiseGit). Get the latest Gir for Windows installer [here](https://github.com/msysgit/msysgit/releases/latest).

**Comment by kenjiuno** [comment]
Thanks, I'll try it!
