### ISSUE TITLE
t2025-checkout-long-paths.sh fails if 8.3 file name support is disabled

### ISSUE THREAD

**Issue by max630** [msysgit/git#338]
Tests `'checkout of long paths without core.longpaths fails'` and `'checkout of long paths with core.longpaths works'` with message "file longpa~1/longtestfile does not exist" if 8.3 file name creation is disabled, like described here: http://support.microsoft.com/en-us/kb/121007

**Comment by dscho** [comment]
That is expected. The unit tests should recapitulate the common setups, and on common setups the 8.3. file name support is enabled. I am sure you agree!
