### ISSUE TITLE
git v2.3.5 is released - When will be available as Windows installer?

### ISSUE THREAD

**Issue by webmaster33** [msysgit/git#340]
git v2.3.5 is released - When will be available as Windows installer?

**Comment by t-b** [comment]
Never, we are switching to CVS as it is fastly superior.

And please use the search, like [here](https://github.com/msysgit/git/issues/331).

**Comment by webmaster33** [comment]
What? Switching to CVS???
Your product name is Git for Windows, so you must be joking...

**Comment by dscho** [comment]
Yep. CVS.

And you are really not permitted [to use the search function](https://github.com/msysgit/git/issues?utf8=✓&q=2.x).

And the earth is flat :smile_cat:

**Comment by dscho** [comment]
Okay

**Comment by dscho** [comment]
(Sorry, reopened by mistake...)
