### ISSUE TITLE
[Portable] git pull doesn't work from git-cmd.bat

### ISSUE THREAD

**Issue by panta82** [msysgit/git#343]
Most of the commands work. But when I try `git pull`, I get this error:

```
The program can't start because libiconv2.dll is missing from your computer
```

There are lots of threads around the internet from 3-4 years ago with similar error. I don't think this is the same problem.

Either way, I followed their solution and copied the dll-s from `msysgit/bin` to `msysgit/libexec/git-core`. This is the error now:

```
trace: built-in: git 'rev-parse' '--git-dir'
trace: built-in: git 'rev-parse' '--is-bare-repository'
trace: built-in: git 'rev-parse' '--show-toplevel'
trace: built-in: git 'ls-files' '-u'
trace: built-in: git 'symbolic-ref' '-q' 'HEAD'
trace: built-in: git 'config' 'branch.master.rebase'
trace: built-in: git 'config' 'pull.rebase'
trace: built-in: git 'rev-parse' '-q' '--verify' 'HEAD'
trace: built-in: git 'fetch' '--update-head-ok'
trace: run_command: 'ssh' 'git@pantas.net' 'git-upload-pack '\''geogrid.git'\'''
error: cannot spawn ssh: No such file or directory
fatal: unable to fork
```

As `git-bash.bat` works fine, it seems like it just doesn't get the proper %PATH% variable more than any problem with repository, config or binaries.

I played a bit with `/msysgit/libexec/git-core/pull`. The best I can tell, the pull bash script gets the correct environment when it is executed. So the problem is probably when `git-pull` calls `git-fetch.exe` and it tries to return from `bash` to `cmd`. Or something?

I tried manually mangling the PATH inside `git-pull` and also the trace env variable. Not sure what else can I try.

Version: Git-1.9.5-preview20150319
Tried on Windows 8.1 64-bit

**Comment by dscho** [comment]
Could you please switch to [Git for Windows 2.x](http://git-for-windows.github.io/) (msysGit-based Git is now retired) and try again? If the bug reoccurs, please [open a bug report there](http://git-for-windows.github.io/#contribute). Thank you.
