### ISSUE TITLE
Msysgit considers all files deleted from index

### ISSUE THREAD

**Issue by einmalfel** [msysgit/git#344]
Hello!

I've got following problem trying to use git on windows with one of my github repositories (for other repos it works fine):
After cloning repo, git status shows all files are both deleted and untracked while files are actually present on file system. I have also noticed (not sure this is relevant) that file .git/index is absent.
Git reset says:
```
$git reset --hard
error: unable to create file thingitwrapper_package/thingitwrapper/aux.py (No such file or directory)
fatal: Could not reset index file to revision 'HEAD'.
```

The repository (https://github.com/einmalfel/git-aflow) doesn't contain files with names longer than 260 chars, nor it contains files with non-ASCII names.

Problem was reproduced with two git builds:
 * git version 1.9.5.msysgit.0, via msys2 shell
 * git version 1.9.5.github.0, via posh-git

**Comment by dscho** [comment]
> `.../aux.py (No such file or directory)`

The name `aux` is not allowed as file name with NTFS. I am sorry, there is nothing Git can do about that...

**Comment by seablackwithink** [comment]
I'm not sure why this file would have been an attempted add...I performed no such request...is this an issue?

**Comment by linquize** [comment]
With filenames `aux`, that's why I cannot checkout the source code of linux kernel on Windows.

**Comment by einmalfel** [comment]
O, really?? I knew this Windows is a weird thing!
Thanks for clarification and sorry for disturbance! Closing the issue..

**Comment by dscho** [comment]
You might be able to work around this as discussed in [this thread](https://groups.google.com/forum/?hl=en#!searchin/msysgit/sparse/msysgit/D4HcHRpxPgU/rzxPLEFDK5wJ), i.e. using sparse checkout or pre-editing of the Git index to avoid invalid filenames.

If you are successful with that strategy, a document on https://github.com/git-for-windows/git/wiki to describe it would be much appreciated.
