### ISSUE TITLE
Feature request: open submodule with git gui

### ISSUE THREAD

**Issue by richardeakin** [msysgit/git#345]
Currently when I try to open a submodule with 'Open an Existing Repository', I get an error message saying 'not a Git repository'. It would be really nice to be able to use the gui when making commits on submodules too.

**Comment by dscho** [comment]
Thank you for your interest in the Git project. A couple of notes:

- From the report it is not clear what steps you performed, in which order. In particular, it is unclear to me what this 'Open an Existing Repository' is. It might be a Start Menu item, but I do not have it. It might be a menu item in the Git GUI, but then I do not find it, either.
- In general, it is a good idea to come up with a [Minimal, Complete and Verifiable Example](http://stackoverflow.com/help/mcve) that helps any volunteer to help you. Please make one.
- Reading "the gui" suggests to me that it might be the Git GUI, or GitHub for Windows, or Visual Studio's Git integration that you are referring to. Please clarify.

**Comment by dscho** [comment]
Hello... *tock, tock tock*, McFly, *tock, tock tock*, anybody home?
