### ISSUE TITLE
Feature request: install tig

### ISSUE THREAD

**Issue by lolive** [msysgit/git#351]
tig is a pretty cool frontend for Git.
https://github.com/jonas/tig

It would be cool to have it ready to run from the Git Bash command-line.

**Comment by dscho** [comment]
I agree that it would be cool if you could have `tig`, but you won't get it for free. Here is what you have to do to get it:

1. Install the [Git SDK](https://git-for-windows.github.io/#download-sdk)
2. Initialize the `MINGW-packages` clone via `cd /usr/src/MINGW-packages && git fetch && git checkout master`
3. Create the `mingw-w64-tig-git/` directory and populate its `PKGBUILD` file (use e.g. [`libosmpbf-git`'s `PKGBUILD` file](https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-libosmpbf-git/PKGBUILD) as an example
4. Build it via `makepkg-mingw -s`
5. Fix build failures (unless there aren't any)
6. Install the package via `pacman -U mingw-w64-*-tig-git*.xz`
7. Test
8. Fix problems (unless there aren't any)
9. Commit, fork [the `MINGW-packages` repository](https://github.com/git-for-windows/MINGW-packages), push and open a Pull Request.

**Comment by dscho** [comment]
Three months is a bit more than I usually wait for feedback.
