### ISSUE TITLE
Using mingw-perl

### ISSUE THREAD

**Issue by Alexpux** [msysgit/git#362]
I'm not an expert in Perl so Ihave a question: what problems to get working git with native Win32 perl?

Also offtopic about https://github.com/git-for-windows/build-extra/blob/master/markdown
Why not use ````markdown```` provided by https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-discount

Regards,
Alexey.

**Comment by dscho** [comment]
> I'm not an expert in Perl so Ihave a question: what problems to get working git with native Win32 perl?

Our most important user of Perl is `git-svn`, requiring the Subversion bindings. As soon as we have that for native Win32 Perl, there is no problem to switch to native Perl.

> Also offtopic about https://github.com/git-for-windows/build-extra/blob/master/markdown
> Why not use markdown provided by https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-discount

My `markdown` package predated yours, and I simply did not have the time to adjust `build-extra`: your `markdown` uses a less intuitive executable name, therefore adjustments are necessary before it will work.

**Comment by dscho** [comment]
BTW you opened this ticket for the Git for Windows 1.x project (which does not use `build-extra`); did you mean to open it for [Git for Windows 2.x](https://github.com/git-for-windows/)?

**Comment by Alexpux** [comment]
Yeah I mean Git4Win2

**Comment by Alexpux** [comment]
Package "discount" provide ````markdown.exe```` executable.

**Comment by dscho** [comment]
Closing here. Please also note that I had substantial trouble last time I tried to get native Perl to work, because we require the Subversion bindings in Perl for `git svn` to work...
