### ISSUE TITLE
git rev-list crashes when --show-notes and --grep are specified

### ISSUE THREAD

**Issue by rick-verint** [msysgit/git#363]
I am trying to learn how notes work, and I don't have any notes in my system yet. While playing around with some commands, I found this bug. Git is from the latest, Git-1.9.5-preview20150319.exe. I am using Windows 7 64 bit.

$ git --version
git version 1.9.5.msysgit.1

$ git rev-list --show-notes --grep '.' HEAD
A
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
ssertion failed: display_notes_trees, file notes.c, line 1270

**Comment by linquize** [comment]
same crash for linux git 2.4.4. Please report to git@vger.kernel.org

**Comment by dscho** [comment]
Moved it to the mailing list myself.
