### ISSUE TITLE
Git SVN crash

### ISSUE THREAD

**Issue by uecasm** [msysgit/git#364]
This is probably similar to the remap errors that I get periodically, but now I'm getting the following, with no hint as to how to make it behave again:

    # git.exe svn fetch
    0 [main] perl.exe" 10724 sync_with_child: child 4256(0x1A4) died before initialization with status code 0xC0000005
    113 [main] perl.exe" 10724 sync_with_child: *** child state waiting for longjmp

It was working yesterday; the only thing I'm aware of that happened between is that my computer rebooted due to a power cut.  "git daemon" was running (but idle) at the time of the power cut, but otherwise nothing git-related was in progress.

I tried reinstalling Git-1.9.5-preview20150319 in case something had been damaged, but this didn't change anything.

**Comment by uecasm** [comment]
And now even trying to run "Git Bash" is doing this:

      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
    AllocationBase 0x68540000, BaseAddress 0x68570000, RegionSize 0xBD0000, State 0x2000
    c:\Program Files (x86)\git\bin\sh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0

**Comment by uecasm** [comment]
Trying different Git-1.9.x versions hasn't helped, but installing Git-2.x instead appears to have resolved this (after https://github.com/git-for-windows/git/issues/233).

**Comment by dscho** [comment]
This looks like the old .dll base address problem. The safe solution is to switch to the 64-bit version of Git for Windows 2.x, indeed.
