### ISSUE TITLE
Git daemon and TortoiseGit

### ISSUE THREAD

**Issue by kenjiuno** [msysgit/git#365]
I'm trying to have synchronized repositories between 2 Windows PCs. Git daemon seems to be simple and I'm trying it.

However it fails to clone.  Are there any known workarounds or such?

command line:
`git.exe clone --progress -v "git://192.168.xxx.xxx/xxx" "C:\Proj\xxx"`

git output using TortoiseGit:
```
Cloning into 'C:\Proj\xxx'...
remote: Counting objects: 228, done.
fatal: early EOF
remote: Compressing objects: 100% (120/120), done.
fatal: read error: Invalid argument
fatal: index-pack failed
```

msysgit  using command line:
```
Cloning into 'C:\Proj\xxx'...
remote: Counting objects: 228, done.
remote: Compressing objects: 100% (120/120), done.
fatal: read error: Invalid argument9.05 MiB | 2.07 MiB/s   s
fatal: early EOF
fatal: index-pack failed
```

**Comment by dscho** [comment]
Is this not a duplicate of the issue described in https://github.com/msysgit/git/pull/70?

**Comment by kenjiuno** [comment]
> Is this not a duplicate of the issue described in #70?

Exactly! I'll check #70 for further investigation. Thanks!
