### ISSUE TITLE
Custom mergetool cmd support in git GUI

### ISSUE THREAD

**Issue by elecpic** [msysgit/git#369]
git GUI doesn't actually support custom mergetool cmd when providing the following .gitconfig:

[merge]
    tool = mymerge
[mergetool]
    cmd = mymerge \"$BASE\" \"$LOCAL\" \"$REMOTE\" -o \"$MERGED\"

Instead git-gui popups the error: "Unsupported merge tool 'mymerge'"

This post: http://stackoverflow.com/a/15984079 directed me to Git/share/git-gui/lib/mergetool.tcl where I fixed the issue in a way to support custom cmd specified in .gitconfig. At least, it works for me...

Here's the file (I didn't find where to attach other than image files):

![mergetool tcl](https://cloud.githubusercontent.com/assets/13475423/8864428/c9d681d8-316f-11e5-9146-944c7727ddc0.jpg)

**Comment by dscho** [comment]
Please fork & clone https://github.com/msysgit/git, patch the problem, provide a proper commit message with sign-off and open a Pull Request.
