### ISSUE TITLE
Filename too long when cloning a repo

### ISSUE THREAD

**Issue by vitaut** [msysgit/git#376]
Here's an example that reproduces the error:

```
C:\1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234>git clone http://github.com/cppformat/cppformat
fatal: could not create work tree dir 'cppformat': Filename too long
```

**Comment by dscho** [comment]
This is a known issue that is [mentioned in the Release Notes along with its resolution](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues):

* Many Windows programs (including the Windows Explorer) have problems with directory trees nested so deeply that the absolute path is longer than 260 characters. Therefore, Git for Windows refuses to check out such files by default. You can overrule this default by setting `core.longPaths`, e.g. `git clone -c core.longPaths=true ...`.

**Comment by dscho** [comment]
Oh, and please note that you posted the issue in the wrong place: Git for Windows 1.x (based on msysGit) is now obsolete, [Git for Windows 2.x](http://git-for-windows.github.io/) superseded it.

**Comment by vitaut** [comment]
Sorry for the wrong bug tracker. I've opened another issue (https://github.com/git-for-windows/git/issues/342) as I get the same error even with `core.longPaths=true`. Thanks!
