### ISSUE TITLE
cloning into a target that is an empty folder is not allowed(but it should?)

### ISSUE THREAD

**Issue by faqindeletethisalready** [msysgit/git#54]
Git for Windows
git-gui version 0.17.GITGUI
git version 1.8.0.msysgit.0

Tcl/Tk version 8.5.11

Hi. 
I start Git Gui, click the Clone Existing Repository link
I enter a source location then I browse to a folder and there I create a new folder by clicking Make New Folder(in the browse window) click ok, I notice the Target Directory specifies the path including this new folder (this is good).
But now I click Clone button and I get an error messagebox(with title "error") saying
`Location <targetdirhere> already exists.`

If I just simply go and delete it, it works. But since it's already empty, I figure maybe gitgui should check if it's empty before showing the error message and only show it if it's not empty. Otherwise you simply cannot select a new folder other than simply selecting existing via Browse button and then appending a `/newfolderhere` in the Target Directory edit box, before pressing Clone.

Thanks for your consideration.

**Comment by dscho** [comment]
@faqindeletethisalready please note that contributions are welcome. So if you want to see this issue fixed, please feel very free to follow the advice on [this page](https://github.com/git-for-windows/git/wiki/How-to-participate), pick up @hvoigt's patch, clean it up and submit a Pull Request.
