### ISSUE TITLE
DCommit fails for files whose path include spaces

### ISSUE THREAD

**Issue by EricGrange** [msysgit/git#90]
What steps will reproduce the problem?
1. create a folder with a space in its name in a git-svn checkout
2. create a file in that folder (doesn't need to have a space in its name)
3. add & commit locally -> works
4. dcommit fails with message about not finding a previous commit

For Git-1.8.3-preview20130601

Typical error is

git.exe svn dcommit

Committing to http://citsrc.cit.local/svn/SVNRepo/trunk ...
M   ProjectName/MigrationTools/v1.28 to v1.29/test.pas

ERROR from SVN:
Filesystem has no item: File not found: transaction '2939-2cw', path '/trunk/ProjectName/MigrationTools/v1.28%20to%20v1.29/test.pas'
W: 175b2eef5983c3a4843152f4091e22b69d4e0ef4 and refs/remotes/git-svn differ, using rebase:
:040000 040000 cf53c85e0a3c71712020f400929ab66ced3b9813 412042bd074e292df06200baea40c12acfd9ea5d M  ProjectName
Current branch master is up to date.
ERROR: Not all changes have been committed into SVN, however the committed
ones (if any) seem to be successfully integrated into the working tree.
Please see the above messages for details.

**Comment by kenorb** [comment]
Related: [How to fix "file not found" on git svn dcommit?](http://stackoverflow.com/q/4664490/55075)

I believe this problem has been fixed for Git >= 1.8.0 and it was related to space handling. But it seems you're using Git-1.8.3, so I don't know.
